package ch.bfh.btx8081.w2013.green;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class Prototyping extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button buttonBack;
	@AutoGenerated
	private ListSelect listSelectSkills;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Prototyping() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:40.0px;left:100.0px;");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:40.0px;left:360.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("240px");
		verticalLayout_1.setHeight("420px");
		verticalLayout_1.setMargin(false);
		
		// listSelectSkills
		listSelectSkills = new ListSelect();
		listSelectSkills.setImmediate(false);
		listSelectSkills.setWidth("240px");
		listSelectSkills.setHeight("380px");
		verticalLayout_1.addComponent(listSelectSkills);
		
		// buttonBack
		buttonBack = new Button();
		buttonBack.setCaption("Back");
		buttonBack.setImmediate(true);
		buttonBack.setWidth("-1px");
		buttonBack.setHeight("-1px");
		verticalLayout_1.addComponent(buttonBack);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("220px");
		absoluteLayout_2.setHeight("420px");
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("212px");
		textArea_1.setHeight("376px");
		absoluteLayout_2.addComponent(textArea_1, "top:4.0px;left:8.0px;");
		
		return absoluteLayout_2;
	}

}
