package mainView;

import com.google.gwt.user.client.ui.HTML;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Layout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.VerticalLayout;

public class MainView01 extends VerticalLayout implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private AbsoluteLayout mainLayout;
	

	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainView01() {
	
	 setWidth("100%");
	 setHeight("100%");
	 

	 Button helpButton = new Button("Help me");
	 helpButton.setDescription("Immediate Help");
	 helpButton.setHeight("200px");
	 
	 Button skillButton = new Button("<b>Skills<b>");
	 skillButton.setDescription("My Skills");
	 
		
	 
	 addComponent(helpButton);
	 addComponent(skillButton);
		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		
//		setImmediate(true);
//		setWidth("100%");
//		setHeight("100%");
//		
//		// top-level component properties
//		setWidth("100.0%");
//		setHeight("100.0%");
//		
//		// buttonHelp
//		Button buttonHelp = new Button("Help");
//		buttonHelp.setImmediate(true);
//		buttonHelp.setDescription("The main view Helpbutton");
//		buttonHelp.setWidth("120px");
//		buttonHelp.setHeight("120px");
//		mainLayout.addComponent(buttonHelp, "top:80.0px;left:60.0px;");
		return mainLayout;
}

	@Override
	public void enter(ViewChangeEvent event) {
		Notification.show("This ist Jan Wiebes homescreen!");
		// TODO Auto-generated method stub
		
	}

}
